name: CI/CD Pipeline - Build & Deploy to ECR + EC2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build-despachos:
    runs-on: ubuntu-latest
    outputs:
      image-uri: ${{ steps.image.outputs.uri }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Despachos
        id: image
        run: |
          REGISTRY="${{ steps.login-ecr.outputs.registry }}"
          REPO="${{ secrets.DESPACHOS_ECR_REPO }}"
          REPO_URI="$REGISTRY/$REPO"
          
          echo "URI Final: '$REPO_URI'"
          
          docker build -t "$REPO_URI" -t "$REPO_URI:latest" back-Despachos_SpringBoot/SPRINGBOOT_API/
          
          docker push "$REPO_URI"
          docker push "$REPO_URI:latest"
          
          echo "uri=$REPO_URI" >> $GITHUB_OUTPUT

  build-ventas:
    runs-on: ubuntu-latest
    outputs:
      image-uri: ${{ steps.image.outputs.uri }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Ventas
        id: image
        run: |
          REGISTRY="${{ steps.login-ecr.outputs.registry }}"
          REPO="${{ secrets.VENTAS_ECR_REPO }}"
          REPO_URI="$REGISTRY/$REPO"
          
          echo "URI Final: '$REPO_URI'"
          
          docker build -t "$REPO_URI" -t "$REPO_URI:latest" back-Despachos_SpringBoot/SPRINGBOOT_API/
          
          docker push "$REPO_URI"
          docker push "$REPO_URI:latest"
          
          echo "uri=$REPO_URI" >> $GITHUB_OUTPUT

  build-frontend:
    runs-on: ubuntu-latest
    outputs:
      image-uri: ${{ steps.image.outputs.uri }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Frontend
        id: image
        run: |
          REGISTRY="${{ steps.login-ecr.outputs.registry }}"
          REPO="${{ secrets.FRONTEND_ECR_REPO }}"
          REPO_URI="$REGISTRY/$REPO"
          
          echo "URI Final: '$REPO_URI'"
          
          docker build -t "$REPO_URI" -t "$REPO_URI:latest" back-Despachos_SpringBoot/SPRINGBOOT_API/
          
          docker push "$REPO_URI"
          docker push "$REPO_URI:latest"
          
          echo "uri=$REPO_URI:${{ github.sha }}" >> $GITHUB_OUTPUT
    
    
  deploy-to-ec2:
    needs: [build-despachos, build-ventas, build-frontend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    env:
      DESPACHOS_IMG: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.DESPACHOS_ECR_REPO }}:latest
      VENTAS_IMG: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.VENTAS_ECR_REPO }}:latest
      FRONTEND_IMG: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.FRONTEND_ECR_REPO }}:latest
      DEPLOY_METHOD: ${{ secrets.DEPLOY_METHOD }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy via SSH
        if: env.DEPLOY_METHOD == 'SSH'
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}

        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

          ssh -i ~/.ssh/id_rsa $USER@$HOST << EOF
            export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
            export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            export AWS_SESSION_TOKEN="${{ secrets.AWS_SESSION_TOKEN }}"
            export AWS_DEFAULT_REGION="${{ env.AWS_REGION }}"
            aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 802319188784.dkr.ecr.us-east-1.amazonaws.com
                 
            sudo -E docker pull ${{ env.DESPACHOS_IMG }}
            echo ${{ env.DESPACHOS_IMG }}
            sudo docker rm -f despachos-api || true
            sudo -E docker run -d --name despachos-api --restart unless-stopped -p 8080:8080 ${{ env.DESPACHOS_IMG }}           
            sudo -E docker pull ${{ env.VENTAS_IMG }}
            echo ${{ env.VENTAS_IMG }}
            sudo docker rm -f ventas-api || true
            sudo -E docker run -d --name ventas-api --restart unless-stopped -p 8081:8080 ${{ env.VENTAS_IMG }}            
            sudo -E docker pull ${{ env.FRONTEND_IMG }}
            echo ${{ env.FRONTEND_IMG }}
            sudo docker rm -f frontend || true
            sudo -E docker run -d --name frontend --restart unless-stopped -p 80:80 ${{ env.FRONTEND_IMG }}
            
            sudo docker image prune -f
          EOF

      - name: Deploy via SSM
        if: env.DEPLOY_METHOD == 'SSM'
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --parameters "commands=[
              \"export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}\",
              \"export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}\",
              \"export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}\",
              \"aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 802319188784.dkr.ecr.us-east-1.amazonaws.com\",
              \"sudo docker pull ${{ env.DESPACHOS_IMG }}\",
              \"echo ${{ env.DESPACHOS_IMG }}\",
              \"sudo docker rm -f despachos-api || true\",
              \"sudo docker run -d --name despachos-api --restart unless-stopped -p 8080:8080 ${{ env.DESPACHOS_IMG }}\",
              \"sudo docker pull ${{ env.VENTAS_IMG }}\",
              \"echo ${{ env.VENTAS_IMG }}\",
              \"sudo docker rm -f ventas-api || true\",
              \"sudo docker run -d --name ventas-api --restart unless-stopped -p 8081:8080 ${{ env.VENTAS_IMG }}\",
              \"sudo docker pull ${{ env.FRONTEND_IMG }}\",
              \"echo ${{ env.FRONTEND_IMG }}\",
              \"sudo docker rm -f frontend || true\",
              \"sudo docker run -d --name frontend --restart unless-stopped -p 80:80 ${{ env.FRONTEND_IMG }}\",
              \"sudo docker image prune -f\"

            ]"
